### ISSUE TITLE
run user-auth happened error: getting user's inbox: content type text/html does not have a factory registered to be parsed

### ISSUE THREAD

**Issue by wlevene** [microsoftgraph/msgraph-training-go#201]
2024/04/04 17:20:16 Error getting user's inbox: content type text/html does not have a factory registered to be parsed
panic: Error getting user's inbox: content type text/html does not have a factory registered to be parsed

<img width="850" alt="image" src="https://github.com/microsoftgraph/msgraph-training-go/assets/1000877/b9fe817e-ecdc-4b41-9046-2a87fd06db72">

**Comment by jasonjoh** [comment]
I recently helped another person who had a similar error here: https://github.com/microsoftgraph/msgraph-training-python/issues/128

In their case, the user they were authenticating as was a personal Microsoft account (not a work or school account), and they had registered their application so that it didn't allow personal accounts. Posting what fixed it in that case:

Ok. Let's try this. If you can register an app and choose "Personal Microsoft accounts only":

![image](https://github.com/microsoftgraph/msgraph-training-python/assets/8966342/3771b95d-8cd6-471f-baba-40f98b878270)

Then on the **Authentication** tab, make sure to turn on **Allow public client flows** (be sure to **Save** after toggling the setting):

![image](https://github.com/microsoftgraph/msgraph-training-python/assets/8966342/09b0d084-0320-4a37-9801-04fa9e86c36f)

Then update the `CLIENT_ID` and `TENANT_ID` in .env. Set `CLIENT_ID` to the new client ID from this app registration, and set `TENANT_ID` to `consumers`.

The end result should be that the prompt is slightly different:

```bash
Go Graph Tutorial

To sign in, use a web browser to open the page https://www.microsoft.com/link and enter the code EQ9N4HVL to authenticate.
```
